# Mod
modName=No Tree Punching
modAuthor=AlcatrazEscapee
modId=notreepunching
modGroup=com.alcatrazescapee
modIssueUrl=https://github.com/alcatrazEscapee/no-tree-punching/issues
modHomeUrl=https://www.curseforge.com/minecraft/mc-mods/no-tree-punching
modDescription=This is a minecraft mod meant to add a little more believability to your first few minutes of minecraft play. It was initially inspired by features from TerraFirmaCraft, but has since been refocused around the titular idea: Blocks don't drop anything if broken with the incorrect tool.

# Java 21 is used for 1.20.5+
modJavaVersion=21

# Versions
minecraftVersion=1.21.1
minecraftVersionRange=[1.21,1.22)

fabricVersion=0.102.0+1.21.1
fabricVersionRange=*
fabricLoaderVersion=0.16.5
fabricLoaderVersionRange=[0.16,)

epsilonVersion=0.5

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=D:\\Program Files\\Eclipse Adoptium\\jdk-21.0.5.11-hotspot